// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9cPPmvosPZJm7NxPyb-NmcKJZEesuGI',
    appId: '1:1096429750320:web:66d375802c34656b3c45f5',
    messagingSenderId: '1096429750320',
    projectId: 'lugar-b6713',
    authDomain: 'lugar-b6713.firebaseapp.com',
    storageBucket: 'lugar-b6713.firebasestorage.app',
    measurementId: 'G-SGCD1QQF6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3HCBEOob4S4uvCUXsZB6oOhD1B9V1hY',
    appId: '1:1096429750320:android:1f250b72dac56ce33c45f5',
    messagingSenderId: '1096429750320',
    projectId: 'lugar-b6713',
    storageBucket: 'lugar-b6713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_Swf882F8wB7XTtCUXm6YOwvv1Kj5E0',
    appId: '1:1096429750320:ios:444c9748437dc50a3c45f5',
    messagingSenderId: '1096429750320',
    projectId: 'lugar-b6713',
    storageBucket: 'lugar-b6713.firebasestorage.app',
    iosBundleId: 'com.example.lugarApp',
  );
}
